# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-ast
    -   id: check-toml
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0f
    hooks:
    -   id: python-check-blanket-noqa
    # -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-no-log-warn
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
    -   id: interrogate
-   repo: https://github.com/codespell-project/codespell
    rev: f7ef43a
    hooks:
    -   id: codespell
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
-   repo: https://github.com/psf/black
    rev: 60a2e8e
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: d21ecbf
    hooks:
    -   id: ruff
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 0b037c2
#     hooks:
#     -   id: mypy
-   repo: https://github.com/PyCQA/isort
    rev: 03a9949
    hooks:
    -   id: isort
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: b412b58
    hooks:
    -   id: pymarkdown
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: df034f88
    hooks:
    -   id: check-poetry
